# Generated by Django 5.0.4 on 2024-05-07 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('streaming', '0002_song_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='name',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
